version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  backend:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=upload_image.settings
    depends_on:
      - db

volumes:
  dbdata:
    name: uploadimageapi_dbdata
