[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "upload_image.settings"

[tool.pylint.MESSAGE_CONTROL]
disable = """
    abstract-method,
    no-member,
"""
enable = "useless-suppression"

[tool.pylint.REPORTS]
reports="no"

[tool.pylint.FORMAT]
max-line-length="88"

[tool.pylint.BASIC]
good-names = "_,i,e,setUp,tearDown,maxDiff"